spring:
  application:
    name: account-service
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/accountdb?createDatabaseIfNotExist=true
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 0
  error:
    include-message: always
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
customProperty:
  test: PavanKumar
management:
  endpoints:
    web:
      exposure:
        include: refresh, health
api:
  customer: http://CUSTOMER-SERVICE/customer
