spring:
  cloud:
    gateway:
      routes:
      - id: ORDER-SERVICE
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/order/**
      - id: ORDER-SERVICE
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/order/**         
server:
  port: 9191
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
        
   
